services:
  ring-server:
    image: ringracers-server:latest
#    environment:
#      - SERVER_NAME="^5Ring Racers ^4Docker ^6Image"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    user: 10001:10001
    ports:
      - 50291:50291/udp
      - 8421:80
    volumes:
      - ./ringdata:/data:z,U
    logging:
      driver: "json-file"
      options:
        max-size: "1MB"
        max-file: "10"

